package main

import (
	"fmt"
	"net/http"
	"text/template"
)

var tem *template.Template

func main() {
	fmt.Println("Initilizating Serer...")

	mux := http.NewServeMux()
	server := http.Server{}

	mux.HandleFunc("/", handleRoot)
	mux.HandleFunc("/cat", handleCat)
	mux.HandleFunc("/dog", handleDog)

	server.Handler = mux
	server.ListenAndServe()
}

func handleRoot(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("<h1>WelCome_Back_MASTER_CCN</h1>"))
	fmt.Fprintf(w, "<h1>HOPE_YOU_ARE_ALL_GOOD_MASTER_CCN</h1>")
	fmt.Fprintf(w, `
		<section>
		  <div style="color:red;" >
		    <h4>navigate to: </h4>  
			  <a href="/cat">CAT</a>  
		  </div>
      <div style="color:blue;" >
		    <h4>navigate to: </h4>  
			  <a href="/dog">DOG</a>  
		  </div>
		</section>
		`)
}

/*
This will simpelly rander the given Text under h1 tag, insted of giving pre tag like before
You can be as creative as you can with this
You can write HTML,CSS,JS or even entire framework like this, but its not intuitive

There is something called template here to help us out in this
*/
func handleCat(w http.ResponseWriter, r *http.Request) {
	tem = template.Must(template.ParseFiles("./htmlFiles/cat.html"))
	tem.Execute(w, nil)
}
func handleDog(w http.ResponseWriter, r *http.Request) {
	tem = template.Must(template.ParseFiles("./htmlFiles/dog.html"))
	tem.Execute(w, nil)
}

/*
This might look devespoting at 1st glance, but its quit easy.
And one more thing,
When you run the server, any change mande to those .html file code will reflect live in  browser
, But if you make change in server it slef (ie this code file ./main.go), Change wont reflect live in clients or any outputs generated by servers
i.e you should re-start the server(Re compile & run)
*/

// Next go to ../try5/main.go
